### ISSUE TITLE
utils method to parse qrbill code into js object

### ISSUE THREAD

**Issue by elvisbegovic** [bbitgmbh/bbit.swiss-qr-bill#127]
# 🚀 Feature request

### Description
just checked https://github.com/bbitgmbh/bbit.swiss-qr-bill/blob/master/src/utils.ts in hope to find a qrcode of qrbill content into js object and didn't find one.

### Solution I'd like
Have a clean way with this lib to uncode/parse a qrbill content into json/js object

Or it maybe exist on your repo anywhere ? I think it should be prety easy to do one since you have needed interfaces here https://github.com/bbitgmbh/bbit.swiss-qr-bill/blob/master/src/interfaces.ts

What you think ?

**Comment by elvisbegovic** [comment]
anyway pretysimple to achieve by `data.split("\n")` and  destructuration

**Comment by thegnuu** [comment]
Would be good to have it in the utils i guess, if you do it anyway - can you make a pull request?

I don't need it until September or so, that's why I have not added it at the moment but i will certainly add it in a future version.
