### ISSUE TITLE
Regex breaking Safari build

### ISSUE THREAD

**Issue by Jan-Vermeulen** [bbitgmbh/bbit.swiss-qr-bill#169]
Hello gals and guys !

The package doesn't work on Safari because of this piece of code:

``` 
private _parseAmount(amount: number): string {
    return amount.toFixed(2).replace(/(?<!\..*)(\d)(?=(?:\d{3})+(?:\.|$))/g, '$1 ');
  }
```
[Lookbehind isn't supported by Safari unfortunately](https://caniuse.com/?search=lookbehind), can you do something about it ? 😊

**Comment by thegnuu** [comment]
Possible ;) We never used our library on Safari, some used in on FF and we just use it in chromium environments....

Unfortunately I don't really have time to look at this issue at the moment. If you can provide a PR I am happy to merge it, if not it might take me some time to find another solution.

**Comment by Jan-Vermeulen** [comment]
Sorry I'm allergic to regex, I'll pass on that 😂 
(Good luck 😄 )
